// Generates server/game.gen.js from index.html.
//
// Cloudflare Workers forbid runtime eval, so the Worker cannot load the game the
// way tools/harness.js does. Instead this bakes the game's script into a real ES
// module at build time: the source goes inside a factory function whose local
// consts shadow the browser globals it expects. The Worker then runs the exact
// same physics the player ran, and re-running this script keeps them in sync.
//
//   node server/build.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'src', 'index.html'), 'utf8');
const src = html.match(/<script>([\s\S]*?)<\/script>/)[1];

const out = `// GENERATED by server/build.js -- do not edit. Run: node server/build.js
// Source: index.html @ ${new Date().toISOString()}
/* eslint-disable */
export function createGame() {
  // --- browser globals the game touches, stubbed. Nothing here draws or sounds.
  const glStub = new Proxy({}, {
    get(t, k) { return k === Symbol.toPrimitive ? () => 1 : (...a) => ({}); }
  });
  const el = () => new Proxy(
    { style: {}, dataset: {}, innerHTML: '', textContent: '', width: 800, height: 600,
      classList: { contains: () => false, add() {}, remove() {}, toggle() {} },
      getContext: () => glStub, addEventListener() {}, removeEventListener() {},
      dispatchEvent() {}, querySelector: () => null, querySelectorAll: () => [],
      getBoundingClientRect: () => ({ left:0, top:0, right:0, bottom:0, width:0, height:0 }) },
    { get(t, k) { return k in t ? t[k] : (...a) => undefined; },
      set(t, k, v) { t[k] = v; return true; } }
  );
  const document = {
    getElementById: () => el(), querySelector: () => null, querySelectorAll: () => [],
    addEventListener() {}, body: el(),
  };
  const requestAnimationFrame = () => 0;
  const performance = { now: () => 0 };
  const matchMedia = () => ({ matches: false, addEventListener() {} });
  const addEventListener = () => {};
  const removeEventListener = () => {};
  const setTimeout = () => 0;
  const clearTimeout = () => {};
  const setInterval = () => 0;
  const clearInterval = () => {};
  const localStorage = { getItem: () => null, setItem() {}, removeItem() {} };
  const console = { log() {}, warn() {}, error() {} };
  const window = {
    AudioContext: undefined, webkitAudioContext: undefined,
    addEventListener() {}, matchMedia, localStorage,
  };
  const atob = (s) => {
    const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    let out = '', buf = 0, bits = 0;
    for (const ch of s) {
      if (ch === '=') break;
      const v = B.indexOf(ch);
      if (v < 0) continue;
      buf = (buf << 6) | v; bits += 6;
      if (bits >= 8) { bits -= 8; out += String.fromCharCode((buf >> bits) & 255); }
    }
    return out;
  };
  const btoa = (s) => {
    const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    let out = '';
    for (let i = 0; i < s.length; i += 3) {
      const a = s.charCodeAt(i), b = s.charCodeAt(i+1), c = s.charCodeAt(i+2);
      out += B[a >> 2] + B[((a & 3) << 4) | (isNaN(b) ? 0 : b >> 4)]
           + (isNaN(b) ? '=' : B[((b & 15) << 2) | (isNaN(c) ? 0 : c >> 6)])
           + (isNaN(c) ? '=' : B[c & 63]);
    }
    return out;
  };

${src.split('\n').map(l => '  ' + l).join('\n')}

  return { G, ST, keys, keyPressed, update, startLevel, LEVELS, BUILD, stepFromMask };
}
`;

const dest = path.join(__dirname, 'game.gen.js');
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(root, dest)}  (${(Buffer.byteLength(out)/1024).toFixed(0)} KB)`);
